# Generated by Django 4.0 on 2021-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('NW', 'Nový úkol'), ('IP', 'V řešení'), ('CM', 'Hotový'), ('CD', 'Zrušený')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
