# Generated by Django 4.0 on 2021-12-20 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_status_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
