# Generated by Django 4.0 on 2021-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todo_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
