# Generated by Django 4.0 on 2021-12-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
