# Generated by Django 4.0 on 2021-12-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo_app', '0007_alter_todo_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
